### PR TITLE
Add initialPositionInStream to options

### PR DESCRIPTION
**Pull request by d-mon-**
Allow `TRIM_HORIZON` when fetching the first records if there is no checkpoint already set.

### CODE REVIEW

**Comment by hy2999la** [comment]
Thank you for adding the `TRIM_HORIZON` iterator type.

https://github.com/d-mon-/lifion-kinesis/blob/trim_horizon/lib/fan-out-consumer.js#L413.

For enhance fanout consumers, is the initialPosition not passed through the iterator type of the stream body? Seems like it is not handled for the fan-out-consumer, after being passed through the options.

**Comment by d-mon-** [comment]
Thank you for spotting this!
This is not a big priority for me right now, but I'll add it to this PR once I get some free time.

**Comment by hy2999la** [comment]
Hey Guerin, thanks for the quick response, I'm part of Lifion, and we wish to take over this ticket. We have a couple releases we wish to make with the ongoing PRs. Thanks and take care!

**Comment by hy2999la** [comment]
Hey there Guerin, We would like to thank you for your contributions, and appreciate your time and your work on this feature! I'll be glad to continue work on the feature and handle adding it to the enhanced fanout consumer.

**Comment by d-mon-** [comment]
Thank you @hy2999la ! I would very much appreciate if you can take over it to include it in your next release as I won't be able to work on this PR until week.

**Pull request merged**
